/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WardlistImport } from './routes/wardlist'
import { Route as UsersImport } from './routes/users'
import { Route as SpeakertrackerImport } from './routes/speakertracker'
import { Route as SacramentmeetingsImport } from './routes/sacramentmeetings'
import { Route as PrayertrackerImport } from './routes/prayertracker'
import { Route as OrganizationsImport } from './routes/organizations'
import { Route as MigrationImport } from './routes/migration'
import { Route as MemberslistImport } from './routes/memberslist'
import { Route as DatafilesImport } from './routes/datafiles'
import { Route as CallingsworkshopImport } from './routes/callingsworkshop'
import { Route as CallingsImport } from './routes/callings'
import { Route as IndexImport } from './routes/index'
import { Route as OrganizationsIdImport } from './routes/organizations.$id'
import { Route as MigrationUsersImport } from './routes/migration.users'
import { Route as MigrationTalksImport } from './routes/migration.talks'
import { Route as MigrationSacramentmeetingsImport } from './routes/migration.sacramentmeetings'
import { Route as MigrationPrayersImport } from './routes/migration.prayers'
import { Route as MigrationMembersImport } from './routes/migration.members'
import { Route as MigrationMembercallingsImport } from './routes/migration.membercallings'
import { Route as MigrationFilesImport } from './routes/migration.files'
import { Route as MigrationCallingworkshopitemsImport } from './routes/migration.callingworkshopitems'
import { Route as MigrationCallingsImport } from './routes/migration.callings'
import { Route as MigrationAssignmentsImport } from './routes/migration.assignments'
import { Route as CallingsIdImport } from './routes/callings.$id'

// Create/Update Routes

const WardlistRoute = WardlistImport.update({
  id: '/wardlist',
  path: '/wardlist',
  getParentRoute: () => rootRoute,
} as any)

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const SpeakertrackerRoute = SpeakertrackerImport.update({
  id: '/speakertracker',
  path: '/speakertracker',
  getParentRoute: () => rootRoute,
} as any)

const SacramentmeetingsRoute = SacramentmeetingsImport.update({
  id: '/sacramentmeetings',
  path: '/sacramentmeetings',
  getParentRoute: () => rootRoute,
} as any)

const PrayertrackerRoute = PrayertrackerImport.update({
  id: '/prayertracker',
  path: '/prayertracker',
  getParentRoute: () => rootRoute,
} as any)

const OrganizationsRoute = OrganizationsImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRoute,
} as any)

const MigrationRoute = MigrationImport.update({
  id: '/migration',
  path: '/migration',
  getParentRoute: () => rootRoute,
} as any)

const MemberslistRoute = MemberslistImport.update({
  id: '/memberslist',
  path: '/memberslist',
  getParentRoute: () => rootRoute,
} as any)

const DatafilesRoute = DatafilesImport.update({
  id: '/datafiles',
  path: '/datafiles',
  getParentRoute: () => rootRoute,
} as any)

const CallingsworkshopRoute = CallingsworkshopImport.update({
  id: '/callingsworkshop',
  path: '/callingsworkshop',
  getParentRoute: () => rootRoute,
} as any)

const CallingsRoute = CallingsImport.update({
  id: '/callings',
  path: '/callings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const OrganizationsIdRoute = OrganizationsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => OrganizationsRoute,
} as any)

const MigrationUsersRoute = MigrationUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => MigrationRoute,
} as any)

const MigrationTalksRoute = MigrationTalksImport.update({
  id: '/talks',
  path: '/talks',
  getParentRoute: () => MigrationRoute,
} as any)

const MigrationSacramentmeetingsRoute = MigrationSacramentmeetingsImport.update(
  {
    id: '/sacramentmeetings',
    path: '/sacramentmeetings',
    getParentRoute: () => MigrationRoute,
  } as any,
)

const MigrationPrayersRoute = MigrationPrayersImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => MigrationRoute,
} as any)

const MigrationMembersRoute = MigrationMembersImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => MigrationRoute,
} as any)

const MigrationMembercallingsRoute = MigrationMembercallingsImport.update({
  id: '/membercallings',
  path: '/membercallings',
  getParentRoute: () => MigrationRoute,
} as any)

const MigrationFilesRoute = MigrationFilesImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => MigrationRoute,
} as any)

const MigrationCallingworkshopitemsRoute =
  MigrationCallingworkshopitemsImport.update({
    id: '/callingworkshopitems',
    path: '/callingworkshopitems',
    getParentRoute: () => MigrationRoute,
  } as any)

const MigrationCallingsRoute = MigrationCallingsImport.update({
  id: '/callings',
  path: '/callings',
  getParentRoute: () => MigrationRoute,
} as any)

const MigrationAssignmentsRoute = MigrationAssignmentsImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => MigrationRoute,
} as any)

const CallingsIdRoute = CallingsIdImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CallingsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/callings': {
      id: '/callings'
      path: '/callings'
      fullPath: '/callings'
      preLoaderRoute: typeof CallingsImport
      parentRoute: typeof rootRoute
    }
    '/callingsworkshop': {
      id: '/callingsworkshop'
      path: '/callingsworkshop'
      fullPath: '/callingsworkshop'
      preLoaderRoute: typeof CallingsworkshopImport
      parentRoute: typeof rootRoute
    }
    '/datafiles': {
      id: '/datafiles'
      path: '/datafiles'
      fullPath: '/datafiles'
      preLoaderRoute: typeof DatafilesImport
      parentRoute: typeof rootRoute
    }
    '/memberslist': {
      id: '/memberslist'
      path: '/memberslist'
      fullPath: '/memberslist'
      preLoaderRoute: typeof MemberslistImport
      parentRoute: typeof rootRoute
    }
    '/migration': {
      id: '/migration'
      path: '/migration'
      fullPath: '/migration'
      preLoaderRoute: typeof MigrationImport
      parentRoute: typeof rootRoute
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsImport
      parentRoute: typeof rootRoute
    }
    '/prayertracker': {
      id: '/prayertracker'
      path: '/prayertracker'
      fullPath: '/prayertracker'
      preLoaderRoute: typeof PrayertrackerImport
      parentRoute: typeof rootRoute
    }
    '/sacramentmeetings': {
      id: '/sacramentmeetings'
      path: '/sacramentmeetings'
      fullPath: '/sacramentmeetings'
      preLoaderRoute: typeof SacramentmeetingsImport
      parentRoute: typeof rootRoute
    }
    '/speakertracker': {
      id: '/speakertracker'
      path: '/speakertracker'
      fullPath: '/speakertracker'
      preLoaderRoute: typeof SpeakertrackerImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/wardlist': {
      id: '/wardlist'
      path: '/wardlist'
      fullPath: '/wardlist'
      preLoaderRoute: typeof WardlistImport
      parentRoute: typeof rootRoute
    }
    '/callings/$id': {
      id: '/callings/$id'
      path: '/$id'
      fullPath: '/callings/$id'
      preLoaderRoute: typeof CallingsIdImport
      parentRoute: typeof CallingsImport
    }
    '/migration/assignments': {
      id: '/migration/assignments'
      path: '/assignments'
      fullPath: '/migration/assignments'
      preLoaderRoute: typeof MigrationAssignmentsImport
      parentRoute: typeof MigrationImport
    }
    '/migration/callings': {
      id: '/migration/callings'
      path: '/callings'
      fullPath: '/migration/callings'
      preLoaderRoute: typeof MigrationCallingsImport
      parentRoute: typeof MigrationImport
    }
    '/migration/callingworkshopitems': {
      id: '/migration/callingworkshopitems'
      path: '/callingworkshopitems'
      fullPath: '/migration/callingworkshopitems'
      preLoaderRoute: typeof MigrationCallingworkshopitemsImport
      parentRoute: typeof MigrationImport
    }
    '/migration/files': {
      id: '/migration/files'
      path: '/files'
      fullPath: '/migration/files'
      preLoaderRoute: typeof MigrationFilesImport
      parentRoute: typeof MigrationImport
    }
    '/migration/membercallings': {
      id: '/migration/membercallings'
      path: '/membercallings'
      fullPath: '/migration/membercallings'
      preLoaderRoute: typeof MigrationMembercallingsImport
      parentRoute: typeof MigrationImport
    }
    '/migration/members': {
      id: '/migration/members'
      path: '/members'
      fullPath: '/migration/members'
      preLoaderRoute: typeof MigrationMembersImport
      parentRoute: typeof MigrationImport
    }
    '/migration/prayers': {
      id: '/migration/prayers'
      path: '/prayers'
      fullPath: '/migration/prayers'
      preLoaderRoute: typeof MigrationPrayersImport
      parentRoute: typeof MigrationImport
    }
    '/migration/sacramentmeetings': {
      id: '/migration/sacramentmeetings'
      path: '/sacramentmeetings'
      fullPath: '/migration/sacramentmeetings'
      preLoaderRoute: typeof MigrationSacramentmeetingsImport
      parentRoute: typeof MigrationImport
    }
    '/migration/talks': {
      id: '/migration/talks'
      path: '/talks'
      fullPath: '/migration/talks'
      preLoaderRoute: typeof MigrationTalksImport
      parentRoute: typeof MigrationImport
    }
    '/migration/users': {
      id: '/migration/users'
      path: '/users'
      fullPath: '/migration/users'
      preLoaderRoute: typeof MigrationUsersImport
      parentRoute: typeof MigrationImport
    }
    '/organizations/$id': {
      id: '/organizations/$id'
      path: '/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof OrganizationsIdImport
      parentRoute: typeof OrganizationsImport
    }
  }
}

// Create and export the route tree

interface CallingsRouteChildren {
  CallingsIdRoute: typeof CallingsIdRoute
}

const CallingsRouteChildren: CallingsRouteChildren = {
  CallingsIdRoute: CallingsIdRoute,
}

const CallingsRouteWithChildren = CallingsRoute._addFileChildren(
  CallingsRouteChildren,
)

interface MigrationRouteChildren {
  MigrationAssignmentsRoute: typeof MigrationAssignmentsRoute
  MigrationCallingsRoute: typeof MigrationCallingsRoute
  MigrationCallingworkshopitemsRoute: typeof MigrationCallingworkshopitemsRoute
  MigrationFilesRoute: typeof MigrationFilesRoute
  MigrationMembercallingsRoute: typeof MigrationMembercallingsRoute
  MigrationMembersRoute: typeof MigrationMembersRoute
  MigrationPrayersRoute: typeof MigrationPrayersRoute
  MigrationSacramentmeetingsRoute: typeof MigrationSacramentmeetingsRoute
  MigrationTalksRoute: typeof MigrationTalksRoute
  MigrationUsersRoute: typeof MigrationUsersRoute
}

const MigrationRouteChildren: MigrationRouteChildren = {
  MigrationAssignmentsRoute: MigrationAssignmentsRoute,
  MigrationCallingsRoute: MigrationCallingsRoute,
  MigrationCallingworkshopitemsRoute: MigrationCallingworkshopitemsRoute,
  MigrationFilesRoute: MigrationFilesRoute,
  MigrationMembercallingsRoute: MigrationMembercallingsRoute,
  MigrationMembersRoute: MigrationMembersRoute,
  MigrationPrayersRoute: MigrationPrayersRoute,
  MigrationSacramentmeetingsRoute: MigrationSacramentmeetingsRoute,
  MigrationTalksRoute: MigrationTalksRoute,
  MigrationUsersRoute: MigrationUsersRoute,
}

const MigrationRouteWithChildren = MigrationRoute._addFileChildren(
  MigrationRouteChildren,
)

interface OrganizationsRouteChildren {
  OrganizationsIdRoute: typeof OrganizationsIdRoute
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsIdRoute: OrganizationsIdRoute,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/callings': typeof CallingsRouteWithChildren
  '/callingsworkshop': typeof CallingsworkshopRoute
  '/datafiles': typeof DatafilesRoute
  '/memberslist': typeof MemberslistRoute
  '/migration': typeof MigrationRouteWithChildren
  '/organizations': typeof OrganizationsRouteWithChildren
  '/prayertracker': typeof PrayertrackerRoute
  '/sacramentmeetings': typeof SacramentmeetingsRoute
  '/speakertracker': typeof SpeakertrackerRoute
  '/users': typeof UsersRoute
  '/wardlist': typeof WardlistRoute
  '/callings/$id': typeof CallingsIdRoute
  '/migration/assignments': typeof MigrationAssignmentsRoute
  '/migration/callings': typeof MigrationCallingsRoute
  '/migration/callingworkshopitems': typeof MigrationCallingworkshopitemsRoute
  '/migration/files': typeof MigrationFilesRoute
  '/migration/membercallings': typeof MigrationMembercallingsRoute
  '/migration/members': typeof MigrationMembersRoute
  '/migration/prayers': typeof MigrationPrayersRoute
  '/migration/sacramentmeetings': typeof MigrationSacramentmeetingsRoute
  '/migration/talks': typeof MigrationTalksRoute
  '/migration/users': typeof MigrationUsersRoute
  '/organizations/$id': typeof OrganizationsIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callings': typeof CallingsRouteWithChildren
  '/callingsworkshop': typeof CallingsworkshopRoute
  '/datafiles': typeof DatafilesRoute
  '/memberslist': typeof MemberslistRoute
  '/migration': typeof MigrationRouteWithChildren
  '/organizations': typeof OrganizationsRouteWithChildren
  '/prayertracker': typeof PrayertrackerRoute
  '/sacramentmeetings': typeof SacramentmeetingsRoute
  '/speakertracker': typeof SpeakertrackerRoute
  '/users': typeof UsersRoute
  '/wardlist': typeof WardlistRoute
  '/callings/$id': typeof CallingsIdRoute
  '/migration/assignments': typeof MigrationAssignmentsRoute
  '/migration/callings': typeof MigrationCallingsRoute
  '/migration/callingworkshopitems': typeof MigrationCallingworkshopitemsRoute
  '/migration/files': typeof MigrationFilesRoute
  '/migration/membercallings': typeof MigrationMembercallingsRoute
  '/migration/members': typeof MigrationMembersRoute
  '/migration/prayers': typeof MigrationPrayersRoute
  '/migration/sacramentmeetings': typeof MigrationSacramentmeetingsRoute
  '/migration/talks': typeof MigrationTalksRoute
  '/migration/users': typeof MigrationUsersRoute
  '/organizations/$id': typeof OrganizationsIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/callings': typeof CallingsRouteWithChildren
  '/callingsworkshop': typeof CallingsworkshopRoute
  '/datafiles': typeof DatafilesRoute
  '/memberslist': typeof MemberslistRoute
  '/migration': typeof MigrationRouteWithChildren
  '/organizations': typeof OrganizationsRouteWithChildren
  '/prayertracker': typeof PrayertrackerRoute
  '/sacramentmeetings': typeof SacramentmeetingsRoute
  '/speakertracker': typeof SpeakertrackerRoute
  '/users': typeof UsersRoute
  '/wardlist': typeof WardlistRoute
  '/callings/$id': typeof CallingsIdRoute
  '/migration/assignments': typeof MigrationAssignmentsRoute
  '/migration/callings': typeof MigrationCallingsRoute
  '/migration/callingworkshopitems': typeof MigrationCallingworkshopitemsRoute
  '/migration/files': typeof MigrationFilesRoute
  '/migration/membercallings': typeof MigrationMembercallingsRoute
  '/migration/members': typeof MigrationMembersRoute
  '/migration/prayers': typeof MigrationPrayersRoute
  '/migration/sacramentmeetings': typeof MigrationSacramentmeetingsRoute
  '/migration/talks': typeof MigrationTalksRoute
  '/migration/users': typeof MigrationUsersRoute
  '/organizations/$id': typeof OrganizationsIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callings'
    | '/callingsworkshop'
    | '/datafiles'
    | '/memberslist'
    | '/migration'
    | '/organizations'
    | '/prayertracker'
    | '/sacramentmeetings'
    | '/speakertracker'
    | '/users'
    | '/wardlist'
    | '/callings/$id'
    | '/migration/assignments'
    | '/migration/callings'
    | '/migration/callingworkshopitems'
    | '/migration/files'
    | '/migration/membercallings'
    | '/migration/members'
    | '/migration/prayers'
    | '/migration/sacramentmeetings'
    | '/migration/talks'
    | '/migration/users'
    | '/organizations/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callings'
    | '/callingsworkshop'
    | '/datafiles'
    | '/memberslist'
    | '/migration'
    | '/organizations'
    | '/prayertracker'
    | '/sacramentmeetings'
    | '/speakertracker'
    | '/users'
    | '/wardlist'
    | '/callings/$id'
    | '/migration/assignments'
    | '/migration/callings'
    | '/migration/callingworkshopitems'
    | '/migration/files'
    | '/migration/membercallings'
    | '/migration/members'
    | '/migration/prayers'
    | '/migration/sacramentmeetings'
    | '/migration/talks'
    | '/migration/users'
    | '/organizations/$id'
  id:
    | '__root__'
    | '/'
    | '/callings'
    | '/callingsworkshop'
    | '/datafiles'
    | '/memberslist'
    | '/migration'
    | '/organizations'
    | '/prayertracker'
    | '/sacramentmeetings'
    | '/speakertracker'
    | '/users'
    | '/wardlist'
    | '/callings/$id'
    | '/migration/assignments'
    | '/migration/callings'
    | '/migration/callingworkshopitems'
    | '/migration/files'
    | '/migration/membercallings'
    | '/migration/members'
    | '/migration/prayers'
    | '/migration/sacramentmeetings'
    | '/migration/talks'
    | '/migration/users'
    | '/organizations/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallingsRoute: typeof CallingsRouteWithChildren
  CallingsworkshopRoute: typeof CallingsworkshopRoute
  DatafilesRoute: typeof DatafilesRoute
  MemberslistRoute: typeof MemberslistRoute
  MigrationRoute: typeof MigrationRouteWithChildren
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  PrayertrackerRoute: typeof PrayertrackerRoute
  SacramentmeetingsRoute: typeof SacramentmeetingsRoute
  SpeakertrackerRoute: typeof SpeakertrackerRoute
  UsersRoute: typeof UsersRoute
  WardlistRoute: typeof WardlistRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallingsRoute: CallingsRouteWithChildren,
  CallingsworkshopRoute: CallingsworkshopRoute,
  DatafilesRoute: DatafilesRoute,
  MemberslistRoute: MemberslistRoute,
  MigrationRoute: MigrationRouteWithChildren,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  PrayertrackerRoute: PrayertrackerRoute,
  SacramentmeetingsRoute: SacramentmeetingsRoute,
  SpeakertrackerRoute: SpeakertrackerRoute,
  UsersRoute: UsersRoute,
  WardlistRoute: WardlistRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/callings",
        "/callingsworkshop",
        "/datafiles",
        "/memberslist",
        "/migration",
        "/organizations",
        "/prayertracker",
        "/sacramentmeetings",
        "/speakertracker",
        "/users",
        "/wardlist"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/callings": {
      "filePath": "callings.tsx",
      "children": [
        "/callings/$id"
      ]
    },
    "/callingsworkshop": {
      "filePath": "callingsworkshop.tsx"
    },
    "/datafiles": {
      "filePath": "datafiles.tsx"
    },
    "/memberslist": {
      "filePath": "memberslist.tsx"
    },
    "/migration": {
      "filePath": "migration.tsx",
      "children": [
        "/migration/assignments",
        "/migration/callings",
        "/migration/callingworkshopitems",
        "/migration/files",
        "/migration/membercallings",
        "/migration/members",
        "/migration/prayers",
        "/migration/sacramentmeetings",
        "/migration/talks",
        "/migration/users"
      ]
    },
    "/organizations": {
      "filePath": "organizations.tsx",
      "children": [
        "/organizations/$id"
      ]
    },
    "/prayertracker": {
      "filePath": "prayertracker.tsx"
    },
    "/sacramentmeetings": {
      "filePath": "sacramentmeetings.tsx"
    },
    "/speakertracker": {
      "filePath": "speakertracker.tsx"
    },
    "/users": {
      "filePath": "users.tsx"
    },
    "/wardlist": {
      "filePath": "wardlist.tsx"
    },
    "/callings/$id": {
      "filePath": "callings.$id.tsx",
      "parent": "/callings"
    },
    "/migration/assignments": {
      "filePath": "migration.assignments.tsx",
      "parent": "/migration"
    },
    "/migration/callings": {
      "filePath": "migration.callings.tsx",
      "parent": "/migration"
    },
    "/migration/callingworkshopitems": {
      "filePath": "migration.callingworkshopitems.tsx",
      "parent": "/migration"
    },
    "/migration/files": {
      "filePath": "migration.files.tsx",
      "parent": "/migration"
    },
    "/migration/membercallings": {
      "filePath": "migration.membercallings.tsx",
      "parent": "/migration"
    },
    "/migration/members": {
      "filePath": "migration.members.tsx",
      "parent": "/migration"
    },
    "/migration/prayers": {
      "filePath": "migration.prayers.tsx",
      "parent": "/migration"
    },
    "/migration/sacramentmeetings": {
      "filePath": "migration.sacramentmeetings.tsx",
      "parent": "/migration"
    },
    "/migration/talks": {
      "filePath": "migration.talks.tsx",
      "parent": "/migration"
    },
    "/migration/users": {
      "filePath": "migration.users.tsx",
      "parent": "/migration"
    },
    "/organizations/$id": {
      "filePath": "organizations.$id.tsx",
      "parent": "/organizations"
    }
  }
}
ROUTE_MANIFEST_END */
